#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sonarr"
name = "Sonarr"
description.en = "Series collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de collection de séries pour utilisateurs de Usenet et BitTorrent"

version = "4.0.19.2979~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://sonarr.tv"
admindoc = "https://wiki.servarr.com/Sonarr"
code = "https://github.com/Sonarr/Sonarr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sonarr"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.19.2979/Sonarr.main.4.0.19.2979.linux-x64.tar.gz"
    amd64.sha256 = "b691b3584c31c0b5514058dee81071c923f63d59a37d19e32f92fa13eaa153db"
    arm64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.19.2979/Sonarr.main.4.0.19.2979.linux-arm64.tar.gz"
    arm64.sha256 = "8d97be4a554b12293c26dbc2a4606f424d7226b522a975048824ecf941a21aa5"
    armhf.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.19.2979/Sonarr.main.4.0.19.2979.linux-arm.tar.gz"
    armhf.sha256 = "98cfa55e7bd9d4ef197ce0e1cc1789509caf033f970d5529ae1f053056ba92d3"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\.linux-x64.tar.gz"
    autoupdate.asset.arm64 = ".*\\.linux-arm64.tar.gz"
    autoupdate.asset.armhf = ".*\\.linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]

    [resources.apt]
    packages = [
        "sqlite3",
        "dirmngr",
        "mediainfo",
    ]
