#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sonarr"
name = "Sonarr"
description.en = "Series collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de collection de séries pour utilisateurs de Usenet et BitTorrent"

version = "4.0.11.2680~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://sonarr.tv"
admindoc = "https://wiki.servarr.com/Sonarr"
code = "https://github.com/Sonarr/Sonarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sonarr"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.11.2680/Sonarr.main.4.0.11.2680.linux-x64.tar.gz"
    amd64.sha256 = "f725097f0a626034b0d2c781789831079bee2913941156c2028c162252020883"
    arm64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.11.2680/Sonarr.main.4.0.11.2680.linux-arm64.tar.gz"
    arm64.sha256 = "85871a87b0e997308fff634e92ccb810f937b9c8c527995dd14db9f9c49e624b"
    armhf.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.11.2680/Sonarr.main.4.0.11.2680.linux-arm.tar.gz"
    armhf.sha256 = "8237e8d69b627e0e5a4e72a4f107effafb62d535c01b36198e67c585405fe578"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\.linux-x64.tar.gz"
    autoupdate.asset.arm64 = ".*\\.linux-arm64.tar.gz"
    autoupdate.asset.armhf = ".*\\.linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = [
        "sqlite3",
        "dirmngr",
        "mediainfo",
    ]
