#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sonarr"
name = "Sonarr"
description.en = "Series collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de collection de séries pour utilisateurs de Usenet et BitTorrent"

version = "4.0.4.1491~ynh2"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://sonarr.tv"
admindoc = "https://wiki.servarr.com/Sonarr"
code = "https://github.com/Sonarr/Sonarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sonarr"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.4.1491/Sonarr.main.4.0.4.1491.linux-x64.tar.gz"
    amd64.sha256 = "aed94e15f7a264bb28651fdb50f02d5a270ad42bbfa71b620611dd1d86c6ac7a"
    arm64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.4.1491/Sonarr.main.4.0.4.1491.linux-arm64.tar.gz"
    arm64.sha256 = "8cca75903542418b4384edbc1e806ea3b2009446a8a8f156f043d85dcd73a4a3"
    armhf.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.4.1491/Sonarr.main.4.0.4.1491.linux-arm.tar.gz"
    armhf.sha256 = "e5ab5367ad73e26fea538134d4181c5a7821795acb9d269dd6b0990461bbc2ea"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\.linux-x64.tar.gz"
    autoupdate.asset.arm64 = ".*\\.linux-arm64.tar.gz"
    autoupdate.asset.armhf = ".*\\.linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = [
        "sqlite3",
        "dirmngr",
        "mediainfo",
    ]
