#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sonarr"
name = "Sonarr"
description.en = "Series collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de collection de séries pour utilisateurs de Usenet et BitTorrent"

version = "4.0.3.1413~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://sonarr.tv"
admindoc = "https://wiki.servarr.com/Sonarr"
code = "https://github.com/Sonarr/Sonarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sonarr"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.3.1413/Sonarr.main.4.0.3.1413.linux-x64.tar.gz"
    amd64.sha256 = "c4668f3443d2a54afdb2fe034caf280c7ce62f2b69dd3a7e729e394354ca62b7"
    arm64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.3.1413/Sonarr.main.4.0.3.1413.linux-arm64.tar.gz"
    arm64.sha256 = "61e1d7232a1c46068798aac4f4af44dfec59c92d8c0e7b3199220907b74040b5"
    armhf.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.3.1413/Sonarr.main.4.0.3.1413.linux-arm.tar.gz"
    armhf.sha256 = "0f79f2d0456239f2f77724a5d7f8464f2103f1b5b4886de814f6cc901fa89384"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\.linux-x64.tar.gz"
    autoupdate.asset.arm64 = ".*\\.linux-arm64.tar.gz"
    autoupdate.asset.armhf = ".*\\.linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    dir = "/var/lib/__APP__"

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = [
        "sqlite3",
        "dirmngr",
        "mediainfo",
    ]
