#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sonarr"
name = "Sonarr"
description.en = "Series collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de collection de séries pour utilisateurs de Usenet et BitTorrent"

version = "3.0.6.1196~ynh2"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://sonarr.tv"
admindoc = "https://wiki.servarr.com/Sonarr"
code = "https://github.com/Sonarr/Sonarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sonarr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "apt-transport-https, dirmngr, gnupg, ca-certificates, mediainfo, mono-devel, sonarr"

        [[resources.apt.extras]]
        repo = "https://download.mono-project.com/repo/debian stable-buster main"
        key = "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
        packages = "mono-devel"

        [[resources.apt.extras]]
        repo = "https://apt.sonarr.tv/debian buster main"
        key = "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2009837CBFFD68F45BC180471F4F90DE2A9B4BF8"
        packages = "sonarr"
