#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sonarr"
name = "Sonarr"
description.en = "Series collection manager for Usenet and BitTorrent users"
description.fr = "Gestionnaire de collection de séries pour utilisateurs de Usenet et BitTorrent"

version = "4.0.18.2971~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0-only"
website = "https://sonarr.tv"
admindoc = "https://wiki.servarr.com/Sonarr"
code = "https://github.com/Sonarr/Sonarr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/sonarr"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.18.2971/Sonarr.main.4.0.18.2971.linux-x64.tar.gz"
    amd64.sha256 = "f7f0a6bd7761e9f4fd5bd9aa68989f0c8c2fdd25d0bac4c245d7d8f9201ecda7"
    arm64.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.18.2971/Sonarr.main.4.0.18.2971.linux-arm64.tar.gz"
    arm64.sha256 = "85727dcd9b7dd8f8603f376179071c442e6f34a196baaaf29268d4e62da4f3bc"
    armhf.url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.18.2971/Sonarr.main.4.0.18.2971.linux-arm.tar.gz"
    armhf.sha256 = "5f206f0e1072bb05c41488b178fda4292babc3c49a0f1e2bb54e6b6ecefdb419"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\.linux-x64.tar.gz"
    autoupdate.asset.arm64 = ".*\\.linux-arm64.tar.gz"
    autoupdate.asset.armhf = ".*\\.linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]

    [resources.apt]
    packages = [
        "sqlite3",
        "dirmngr",
        "mediainfo",
    ]
