#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.a496362.name = "Upgrade from 3.0.6.1196~ynh2"
    test_upgrade_from.a496362.args.domain = "sub.domain.tld"
    test_upgrade_from.a496362.args.path = "/sonarr"
    test_upgrade_from.a496362.args.admin = "package_checker"
