#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin="john"

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.768c1ce50ab30dd77f8863cf68269038a0f0f238.name = "Last packaging v1 version"
