#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.768c1ce.name = "Upgrade from 3.0.6.1196~ynh3 (packaging v1)"
    test_upgrade_from.768c1ce.args.domain = "domain.tld"
    test_upgrade_from.768c1ce.args.path = "/sonarr"
    test_upgrade_from.768c1ce.args.admin = "package_checker"
