#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.768c1ce50ab30dd77f8863cf68269038a0f0f238.name = "Latest packaging v1 version"
    test_upgrade_from.768c1ce50ab30dd77f8863cf68269038a0f0f238.args.domain = "sub.domain.tld"
    test_upgrade_from.768c1ce50ab30dd77f8863cf68269038a0f0f238.args.path = "/sonarr"
    test_upgrade_from.768c1ce50ab30dd77f8863cf68269038a0f0f238.args.admin = "package_checker"
