#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Generate API key for configuration later
api_key=$(ynh_string_random --length=32)
ynh_app_setting_set --app=$app --key="api_key" --value="$api_key"

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring Radarr..." --weight=2

mkdir -p "/var/log/$app"
ln -s "/var/log/$app" "$data_dir/logs"

ynh_add_config --template="config.xml" --destination="$data_dir/config.xml"

chmod 750 "$data_dir"
chmod -R o-rwx "$data_dir"
chown -R "$app:$app" "$data_dir"

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression --message="Adding multimedia directories..." --weight=2

# Build YunoHost multimedia directories
ynh_multimedia_build_main_dir
# Enable writing into these directories
ynh_multimedia_addaccess "$app"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config, it will override the one in /lib/systemd/system/sonarr.service
ynh_add_systemd_config
yunohost service add "$app" --description="Sonarr daemon" --log="/var/log/$app/sonarr.txt"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate --logfile="/var/log/$app/"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=2

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd" --line_match="Starting Web Server" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
